### ISSUE TITLE
missing import time in FeGenie

### ISSUE THREAD

**Issue by michoug** [Arkadiy-Garber/MagicLamp#4]
Hi,
I got this error when running the FeGenie pipeline

```
Traceback (most recent call last):
  File "/home/gmichoud/MagicLamp/MagicLamp.py", line 28, in <module>
    FeGenie.main()
  File "/home/gmichoud/MagicLamp/genies/FeGenie.py", line 843, in main
    time.sleep(5)
NameError: name 'time' is not defined
```

Adding an `import time` in the `FeGenie.py` script solved the issue
Best
Greg

**Comment by Arkadiy-Garber** [comment]
Hi Greg,

Thanks for the heads up about this bug! Glad it was an easy fix. I'll update the scripts.

Cheers,
Arkadiy
