### ISSUE TITLE
BVCN-examples in Issue: Tutorial 2: HMM development and calibration, HmmGenie

### ISSUE THREAD

**Issue by Tsingsjeen** [Arkadiy-Garber/MagicLamp#6]
All required arguments provided!

Finding ORFs for Acidithiobacillus_ferrooxidans.txt
Finding ORFs for Mariprofundus_ferrooxidans_PV-1.txt
Finding ORFs for Rhodopseudomonas_palustris_TIE-1.txt
Finding ORFs for Shewanella_oneidensis_MR-1.txt
starting main pipeline...
Traceback (most recent call last):xidans.txt: 25%
  File "~/MagicLamp/MagicLamp.py", line 46, in <module>
    HmmGenie.main()
  File "~/MagicLamp/genies/HmmGenie.py", line 788, in main
    % (metaDict[hmm]["evalue"], int(args.t), outDirectory, i, hmm, outDirectory, i, hmm, args.hmm_dir, hmm, outDirectory, i))
UnboundLocalError: local variable 'metaDict' referenced before assignment

**Comment by Arkadiy-Garber** [comment]
Hi there, could you please send the command that you used that generated this error?

Thanks!
Arkadiy

**Comment by Tsingsjeen** [comment]
MagicLamp.py HmmGenie -hmm_dir ~/HMMs/dehalo -hmm_ext hmm -bin_dir ~/reassembled_bins/  -bin_ext fa -out dehalo/ -eval 1E-15

Thanks! 

I run the university server, they come to this problem. but for the BVCN-binder, there are no issues. Do you know what happened?

**Comment by Tsingsjeen** [comment]
It may be the university server's problem.

**Comment by Arkadiy-Garber** [comment]
Sorry about that, the program has had some updates since that BVCN-binder was created, so there may have been some issues/bugs that popped up. I addressed what seems to be the cause of the above issue. Please try again with a fresh git clone, and let me know if there are issues that continue.

Also, as an FYI, this software does not recognize the '~' character, so please ask the user to use the full path to each file or directory.

Thanks,
Arkadiy

**Comment by Tsingsjeen** [comment]
I am refreshed the MagicLamp installation and running, but there is also the same problem about the Hmmgenie to run the tutorial and the details are below:

(magiclamp) Chen@potato.wurnet.nl:/work/chen03/marine_AB/chen_run/meta_DR/fun_magic/test$ MagicLamp.py HmmGenie -hmm_dir HMMs/ -hmm_ext hmm -bin_dir test_data/ -bin_ext txt -out hmmgenie_out -bit HMMs/bitscores.txt
rm: cannot remove 'mainDir.txt': No such file or directory
checking arguments
.
.
.
All required arguments provided!

Finding ORFs for Acidithiobacillus_ferrooxidans.txt
Finding ORFs for Mariprofundus_ferrooxidans_PV-1.txt
Finding ORFs for Rhodopseudomonas_palustris_TIE-1.txt
Finding ORFs for Shewanella_oneidensis_MR-1.txt

Starting main pipeline...
**Failed to parse command line: Option -E takes real-valued arg; got EMPTY on cmdline
Usage: hmmsearch [options] <hmmfile> <seqdb>

where most common options are:
  -h : show brief help on version and usage

To see more help on available options, do hmmsearch -h

rm: cannot remove 'hmmgenie_out/Acidithiobacillus_ferrooxidans.txt-HMM/MtrC_TIGR03507.hmm.txt': No such file or directory
Traceback (most recent call last):
  File "/work/chen03/pkgs_db/MagicLamp/MagicLamp.py", line 46, in <module>
    HmmGenie.main()
  File "/work/chen03/pkgs_db/MagicLamp/genies/HmmGenie.py", line 688, in main
    hmmout = open(outDirectory + "/" + i + "-HMM/" + hmm + ".tblout", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'hmmgenie_out/Acidithiobacillus_ferrooxidans.txt-HMM/MtrC_TIGR03507.hmm.tblout'**

Do you you what happened?

Thanks!

**Comment by Arkadiy-Garber** [comment]
Hi @Tsingsjeen,

Sorry for the year-long delay in getting back to this.  HmmGenie has undergone recent changes, including to the above code block where the error is traced to. So please let me know if you're still having issues.

Thanks,
Arkadiy
